### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by caesar** [sindresorhus/load-json-file#11]
It would be useful to be able to know what the breaking changes are in a semver-major release.

http://keepachangelog.com/ :-)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/load-json-file/commits/master

**Comment by caesar** [comment]
Well, yeah, but then everyone has to pick through and try and identify which commit is the breaking change. The whole point of a changelog is to avoid that.

(In this case the breaking change is something in parse-json – I haven't had time to figure out what yet – but since it doesn't have a changelog either, the same applies.)
