### ISSUE TITLE
Error when json file is not found?

### ISSUE THREAD

**Issue by radiovisual** [sindresorhus/load-json-file#2]
Should this module error when the json file is not found, or does this module assume that the file exists?

I have this function:

``` js
function test() {
    console.log("test function called");

    loadJsonFile(jsonpath).then(function (json) {
        console.log("json data: ", json);
    })
}
```

The very first `console.log()` statement always prints to the console, but the second `console.log()` statement only prints if the file at `jsonpath` exists, but if the json file doesn't exist, nothing happens.  Should a "file not found" (`ENOENT`) error be included in the list of helpful errors, or should we be doing our own checks to see if the file exists before calling this module?

BTW: Thanks for all the awesome work you do!

**Comment by sindresorhus** [comment]
Promises supresses errors by default. It's up to you to handle them. Nothing specifically to do with this module though.

Maybe read up on promises: https://github.com/mattdesl/promise-cookbook

``` js
function test() {
    console.log("test function called");

    loadJsonFile(jsonpath).then(function (json) {
        console.log("json data: ", json);
    }).catch(function (err) {
        console.error(err);
    }):
}
```

**Comment by radiovisual** [comment]
ah! I should have known it was something simple. Thanks!
