### ISSUE TITLE
problem with nodejs v0.10 and v0.12: "SyntaxError: Use of const in strict mode."

### ISSUE THREAD

**Issue by iamstarkov** [sindresorhus/load-json-file#6]
ref: https://travis-ci.org/iamstarkov/load-json-file/jobs/129882144#L248

as far as v0.10 and v0.12 are still LTS, i would appreciate support for this nodejs versions. what do you think?

**Comment by sindresorhus** [comment]
Both 0.10 and 0.12 are out of active LTS. Just keep using v1.1.0 if you need to support those versions.

**Comment by iamstarkov** [comment]
takker mye!
