### ISSUE TITLE
Add option to pas through strip-json-comments

### ISSUE THREAD

**Issue by tomyam1** [sindresorhus/load-json-file#7]
It'd be really nice to pass the file through [strip-json-comments](https://github.com/sindresorhus/strip-json-comments)

**Comment by sindresorhus** [comment]
I don't see the point. It has one option and it's not useful here.

**Comment by slavafomin** [comment]
Hello!

I would agree with @tomyam1 that this would be a very convenient feature to have. I need to parse `tsconfig.json` files and they do support comments. Right now this module chokes on such files.

**Comment by tomyam1** [comment]
@slavafomin You can do it easily now with the [beforeParse](https://github.com/sindresorhus/load-json-file#beforeparse) option

**Comment by slavafomin** [comment]
Or, at least this should be added to the examples:

```js
const loadJsonFile = require('load-json-file');
const stripJsonComments = require('strip-json-comments');

const source = await loadJsonFile(file, {
  beforeParse: stripJsonComments,
});
```

**Comment by slavafomin** [comment]
> @slavafomin You can do it easily now with the [beforeParse](https://github.com/sindresorhus/load-json-file#beforeparse) option

Yeah, I know thanks. However, this requires extra dependency and configuration.
